[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[build]
jobs = 8

[profile.dev]
opt-level = 1
codegen-units = 256
split-debuginfo = "unpacked"
debug = "limited"
incremental = true

[profile.dev-minimal]
inherits = "dev"
opt-level = 0
codegen-units = 256

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 4
strip = true

[profile.leptos-dev]
inherits = "dev-minimal"
split-debuginfo = "unpacked"
debug = "line-tables-only"

[alias]
check-fast = "check --all"
